// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_LISTENER_METHOD0
typedef void (*UniffiCallbackInterfaceEventListenerMethod0)(uint64_t, uint32_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_LISTENER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_LISTENER
typedef struct UniffiVTableCallbackInterfaceEventListener {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceEventListenerMethod0 _Nonnull onEvent;
} UniffiVTableCallbackInterfaceEventListener;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_CLONE_DCAPP
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_CLONE_DCAPP
uint64_t uniffi_dcvm_fn_clone_dcapp(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_FREE_DCAPP
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_FREE_DCAPP
void uniffi_dcvm_fn_free_dcapp(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_CONSTRUCTOR_DCAPP_NEW
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_CONSTRUCTOR_DCAPP_NEW
uint64_t uniffi_dcvm_fn_constructor_dcapp_new(RustBuffer data_dir, uint64_t listener
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_ACCEPT_CHAT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_ACCEPT_CHAT
uint64_t uniffi_dcvm_fn_method_dcapp_accept_chat(uint64_t ptr, uint32_t account_id, uint32_t chat_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_ACCOUNTS
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_ACCOUNTS
uint64_t uniffi_dcvm_fn_method_dcapp_accounts(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_ADD_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_ADD_ACCOUNT
uint64_t uniffi_dcvm_fn_method_dcapp_add_account(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_ADD_DEMO_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_ADD_DEMO_ACCOUNT
uint64_t uniffi_dcvm_fn_method_dcapp_add_demo_account(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_ARCHIVED_CHATS
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_ARCHIVED_CHATS
uint64_t uniffi_dcvm_fn_method_dcapp_archived_chats(uint64_t ptr, uint32_t account_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_BLOCK_CHAT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_BLOCK_CHAT
uint64_t uniffi_dcvm_fn_method_dcapp_block_chat(uint64_t ptr, uint32_t account_id, uint32_t chat_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CANCEL_ONGOING
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CANCEL_ONGOING
uint64_t uniffi_dcvm_fn_method_dcapp_cancel_ongoing(uint64_t ptr, uint32_t account_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CHAT_LIST
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CHAT_LIST
uint64_t uniffi_dcvm_fn_method_dcapp_chat_list(uint64_t ptr, uint32_t account_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CHECK_QR
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CHECK_QR
uint64_t uniffi_dcvm_fn_method_dcapp_check_qr(uint64_t ptr, uint32_t account_id, RustBuffer qr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CONNECTIVITY
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CONNECTIVITY
uint64_t uniffi_dcvm_fn_method_dcapp_connectivity(uint64_t ptr, uint32_t account_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CONTACTS
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CONTACTS
uint64_t uniffi_dcvm_fn_method_dcapp_contacts(uint64_t ptr, uint32_t account_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CREATE_CHAT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CREATE_CHAT
uint64_t uniffi_dcvm_fn_method_dcapp_create_chat(uint64_t ptr, uint32_t account_id, RustBuffer email, RustBuffer name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CREATE_GROUP
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CREATE_GROUP
uint64_t uniffi_dcvm_fn_method_dcapp_create_group(uint64_t ptr, uint32_t account_id, RustBuffer name, RustBuffer member_contact_ids
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CREATE_INSTANT_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_CREATE_INSTANT_ACCOUNT
uint64_t uniffi_dcvm_fn_method_dcapp_create_instant_account(uint64_t ptr, uint32_t account_id, RustBuffer display_name, RustBuffer instance
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_DELETE_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_DELETE_MESSAGES
uint64_t uniffi_dcvm_fn_method_dcapp_delete_messages(uint64_t ptr, uint32_t account_id, RustBuffer msg_ids
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_FORWARD_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_FORWARD_MESSAGES
uint64_t uniffi_dcvm_fn_method_dcapp_forward_messages(uint64_t ptr, uint32_t account_id, RustBuffer msg_ids, uint32_t chat_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_JOIN_SECOND_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_JOIN_SECOND_DEVICE
uint64_t uniffi_dcvm_fn_method_dcapp_join_second_device(uint64_t ptr, uint32_t account_id, RustBuffer qr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_LOGIN
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_LOGIN
uint64_t uniffi_dcvm_fn_method_dcapp_login(uint64_t ptr, uint32_t account_id, RustBuffer addr, RustBuffer password
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_MARK_NOTICED
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_MARK_NOTICED
uint64_t uniffi_dcvm_fn_method_dcapp_mark_noticed(uint64_t ptr, uint32_t account_id, uint32_t chat_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_MARK_SEEN
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_MARK_SEEN
uint64_t uniffi_dcvm_fn_method_dcapp_mark_seen(uint64_t ptr, uint32_t account_id, RustBuffer msg_ids
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_MAYBE_NETWORK
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_MAYBE_NETWORK
uint64_t uniffi_dcvm_fn_method_dcapp_maybe_network(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_MESSAGES
uint64_t uniffi_dcvm_fn_method_dcapp_messages(uint64_t ptr, uint32_t account_id, uint32_t chat_id, uint32_t limit, RustBuffer before_msg_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_REMOVE_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_REMOVE_ACCOUNT
uint64_t uniffi_dcvm_fn_method_dcapp_remove_account(uint64_t ptr, uint32_t id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SEARCH_CHATS
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SEARCH_CHATS
uint64_t uniffi_dcvm_fn_method_dcapp_search_chats(uint64_t ptr, uint32_t account_id, RustBuffer query
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SEARCH_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SEARCH_MESSAGES
uint64_t uniffi_dcvm_fn_method_dcapp_search_messages(uint64_t ptr, uint32_t account_id, RustBuffer query
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SELECT_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SELECT_ACCOUNT
uint64_t uniffi_dcvm_fn_method_dcapp_select_account(uint64_t ptr, uint32_t id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SELECTED_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SELECTED_ACCOUNT
RustBuffer uniffi_dcvm_fn_method_dcapp_selected_account(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SEND_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SEND_MESSAGE
uint64_t uniffi_dcvm_fn_method_dcapp_send_message(uint64_t ptr, uint32_t account_id, uint32_t chat_id, RustBuffer text, RustBuffer file_path, RustBuffer quoted_msg_id
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SEND_REACTION
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SEND_REACTION
uint64_t uniffi_dcvm_fn_method_dcapp_send_reaction(uint64_t ptr, uint32_t account_id, uint32_t msg_id, RustBuffer emoji
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SEND_TEXT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SEND_TEXT
uint64_t uniffi_dcvm_fn_method_dcapp_send_text(uint64_t ptr, uint32_t account_id, uint32_t chat_id, RustBuffer text
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SET_AVATAR
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SET_AVATAR
uint64_t uniffi_dcvm_fn_method_dcapp_set_avatar(uint64_t ptr, uint32_t account_id, RustBuffer path
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SET_CHAT_ARCHIVED
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SET_CHAT_ARCHIVED
uint64_t uniffi_dcvm_fn_method_dcapp_set_chat_archived(uint64_t ptr, uint32_t account_id, uint32_t chat_id, int8_t archived
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SET_CHAT_MUTED
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SET_CHAT_MUTED
uint64_t uniffi_dcvm_fn_method_dcapp_set_chat_muted(uint64_t ptr, uint32_t account_id, uint32_t chat_id, int8_t muted
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SET_DISPLAY_NAME
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_SET_DISPLAY_NAME
uint64_t uniffi_dcvm_fn_method_dcapp_set_display_name(uint64_t ptr, uint32_t account_id, RustBuffer name
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_START_IO
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_START_IO
uint64_t uniffi_dcvm_fn_method_dcapp_start_io(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_STOP_IO
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_DCAPP_STOP_IO
uint64_t uniffi_dcvm_fn_method_dcapp_stop_io(uint64_t ptr
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_CLONE_EVENTLISTENER
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_CLONE_EVENTLISTENER
uint64_t uniffi_dcvm_fn_clone_eventlistener(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_FREE_EVENTLISTENER
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_FREE_EVENTLISTENER
void uniffi_dcvm_fn_free_eventlistener(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_INIT_CALLBACK_VTABLE_EVENTLISTENER
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_INIT_CALLBACK_VTABLE_EVENTLISTENER
void uniffi_dcvm_fn_init_callback_vtable_eventlistener(const UniffiVTableCallbackInterfaceEventListener* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_EVENTLISTENER_ON_EVENT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_METHOD_EVENTLISTENER_ON_EVENT
void uniffi_dcvm_fn_method_eventlistener_on_event(uint64_t ptr, uint32_t account_id, RustBuffer event, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_FN_FUNC_DEFAULT_INSTANCE_URL
#define UNIFFI_FFIDEF_UNIFFI_DCVM_FN_FUNC_DEFAULT_INSTANCE_URL
RustBuffer uniffi_dcvm_fn_func_default_instance_url(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_DCVM_RUSTBUFFER_ALLOC
RustBuffer ffi_dcvm_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_DCVM_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_dcvm_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_DCVM_RUSTBUFFER_FREE
void ffi_dcvm_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_DCVM_RUSTBUFFER_RESERVE
RustBuffer ffi_dcvm_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_U8
void ffi_dcvm_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_U8
void ffi_dcvm_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_U8
void ffi_dcvm_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_dcvm_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_I8
void ffi_dcvm_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_I8
void ffi_dcvm_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_I8
void ffi_dcvm_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_I8
int8_t ffi_dcvm_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_U16
void ffi_dcvm_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_U16
void ffi_dcvm_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_U16
void ffi_dcvm_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_dcvm_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_I16
void ffi_dcvm_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_I16
void ffi_dcvm_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_I16
void ffi_dcvm_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_I16
int16_t ffi_dcvm_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_U32
void ffi_dcvm_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_U32
void ffi_dcvm_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_U32
void ffi_dcvm_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_dcvm_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_I32
void ffi_dcvm_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_I32
void ffi_dcvm_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_I32
void ffi_dcvm_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_I32
int32_t ffi_dcvm_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_U64
void ffi_dcvm_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_U64
void ffi_dcvm_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_U64
void ffi_dcvm_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_dcvm_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_I64
void ffi_dcvm_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_I64
void ffi_dcvm_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_I64
void ffi_dcvm_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_I64
int64_t ffi_dcvm_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_F32
void ffi_dcvm_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_F32
void ffi_dcvm_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_F32
void ffi_dcvm_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_F32
float ffi_dcvm_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_F64
void ffi_dcvm_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_F64
void ffi_dcvm_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_F64
void ffi_dcvm_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_F64
double ffi_dcvm_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_dcvm_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_dcvm_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_dcvm_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_dcvm_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_POLL_VOID
void ffi_dcvm_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_CANCEL_VOID
void ffi_dcvm_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_FREE_VOID
void ffi_dcvm_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_DCVM_RUST_FUTURE_COMPLETE_VOID
void ffi_dcvm_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_FUNC_DEFAULT_INSTANCE_URL
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_FUNC_DEFAULT_INSTANCE_URL
uint16_t uniffi_dcvm_checksum_func_default_instance_url(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_ACCEPT_CHAT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_ACCEPT_CHAT
uint16_t uniffi_dcvm_checksum_method_dcapp_accept_chat(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_ACCOUNTS
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_ACCOUNTS
uint16_t uniffi_dcvm_checksum_method_dcapp_accounts(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_ADD_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_ADD_ACCOUNT
uint16_t uniffi_dcvm_checksum_method_dcapp_add_account(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_ADD_DEMO_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_ADD_DEMO_ACCOUNT
uint16_t uniffi_dcvm_checksum_method_dcapp_add_demo_account(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_ARCHIVED_CHATS
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_ARCHIVED_CHATS
uint16_t uniffi_dcvm_checksum_method_dcapp_archived_chats(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_BLOCK_CHAT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_BLOCK_CHAT
uint16_t uniffi_dcvm_checksum_method_dcapp_block_chat(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CANCEL_ONGOING
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CANCEL_ONGOING
uint16_t uniffi_dcvm_checksum_method_dcapp_cancel_ongoing(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CHAT_LIST
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CHAT_LIST
uint16_t uniffi_dcvm_checksum_method_dcapp_chat_list(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CHECK_QR
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CHECK_QR
uint16_t uniffi_dcvm_checksum_method_dcapp_check_qr(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CONNECTIVITY
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CONNECTIVITY
uint16_t uniffi_dcvm_checksum_method_dcapp_connectivity(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CONTACTS
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CONTACTS
uint16_t uniffi_dcvm_checksum_method_dcapp_contacts(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CREATE_CHAT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CREATE_CHAT
uint16_t uniffi_dcvm_checksum_method_dcapp_create_chat(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CREATE_GROUP
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CREATE_GROUP
uint16_t uniffi_dcvm_checksum_method_dcapp_create_group(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CREATE_INSTANT_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_CREATE_INSTANT_ACCOUNT
uint16_t uniffi_dcvm_checksum_method_dcapp_create_instant_account(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_DELETE_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_DELETE_MESSAGES
uint16_t uniffi_dcvm_checksum_method_dcapp_delete_messages(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_FORWARD_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_FORWARD_MESSAGES
uint16_t uniffi_dcvm_checksum_method_dcapp_forward_messages(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_JOIN_SECOND_DEVICE
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_JOIN_SECOND_DEVICE
uint16_t uniffi_dcvm_checksum_method_dcapp_join_second_device(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_LOGIN
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_LOGIN
uint16_t uniffi_dcvm_checksum_method_dcapp_login(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_MARK_NOTICED
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_MARK_NOTICED
uint16_t uniffi_dcvm_checksum_method_dcapp_mark_noticed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_MARK_SEEN
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_MARK_SEEN
uint16_t uniffi_dcvm_checksum_method_dcapp_mark_seen(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_MAYBE_NETWORK
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_MAYBE_NETWORK
uint16_t uniffi_dcvm_checksum_method_dcapp_maybe_network(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_MESSAGES
uint16_t uniffi_dcvm_checksum_method_dcapp_messages(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_REMOVE_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_REMOVE_ACCOUNT
uint16_t uniffi_dcvm_checksum_method_dcapp_remove_account(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SEARCH_CHATS
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SEARCH_CHATS
uint16_t uniffi_dcvm_checksum_method_dcapp_search_chats(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SEARCH_MESSAGES
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SEARCH_MESSAGES
uint16_t uniffi_dcvm_checksum_method_dcapp_search_messages(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SELECT_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SELECT_ACCOUNT
uint16_t uniffi_dcvm_checksum_method_dcapp_select_account(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SELECTED_ACCOUNT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SELECTED_ACCOUNT
uint16_t uniffi_dcvm_checksum_method_dcapp_selected_account(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SEND_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SEND_MESSAGE
uint16_t uniffi_dcvm_checksum_method_dcapp_send_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SEND_REACTION
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SEND_REACTION
uint16_t uniffi_dcvm_checksum_method_dcapp_send_reaction(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SEND_TEXT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SEND_TEXT
uint16_t uniffi_dcvm_checksum_method_dcapp_send_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SET_AVATAR
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SET_AVATAR
uint16_t uniffi_dcvm_checksum_method_dcapp_set_avatar(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SET_CHAT_ARCHIVED
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SET_CHAT_ARCHIVED
uint16_t uniffi_dcvm_checksum_method_dcapp_set_chat_archived(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SET_CHAT_MUTED
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SET_CHAT_MUTED
uint16_t uniffi_dcvm_checksum_method_dcapp_set_chat_muted(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SET_DISPLAY_NAME
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_SET_DISPLAY_NAME
uint16_t uniffi_dcvm_checksum_method_dcapp_set_display_name(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_START_IO
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_START_IO
uint16_t uniffi_dcvm_checksum_method_dcapp_start_io(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_STOP_IO
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_DCAPP_STOP_IO
uint16_t uniffi_dcvm_checksum_method_dcapp_stop_io(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_EVENTLISTENER_ON_EVENT
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_METHOD_EVENTLISTENER_ON_EVENT
uint16_t uniffi_dcvm_checksum_method_eventlistener_on_event(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_CONSTRUCTOR_DCAPP_NEW
#define UNIFFI_FFIDEF_UNIFFI_DCVM_CHECKSUM_CONSTRUCTOR_DCAPP_NEW
uint16_t uniffi_dcvm_checksum_constructor_dcapp_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_DCVM_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_DCVM_UNIFFI_CONTRACT_VERSION
uint32_t ffi_dcvm_uniffi_contract_version(void
    
);
#endif

